[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "conlanger"
dynamic = ["version"]
requires-python = ">= 3.12"
readme = "README.md"

dependencies = [
    # "cldfbench_wals @ git+https://github.com/cldf-datasets/wals.git@v2020#egg=cldfbench_wals",
    "requests",
    "ipykernel",
    "matplotlib",
    "tensorflow",
    "keras",
    "pandas",
    "scikit-learn",
    "tqdm",
    "imbalanced-learn",
    "pyyaml>=6.0.3",
    "pydantic>=2.13.4",
]

[project.scripts]
create_index = "conlanger.scripts.create_index:main"
sample_asca_guess_fixtures = "conlanger.scripts.sample_asca_guess_fixtures:main"

[project.optional-dependencies]
testing = ["pytest", "pytest-cov", "pytest-mock"]
cuda = ["tensorflow[and-cuda]"]

[tool.setuptools.dynamic]
version = { attr = "conlanger.__VERSION__" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "notebooks"]

[tool.setuptools.package-data]
conlanger = ["data/*.csv", "data/asca/*.csv"]

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = ["tests"]
addopts = ["--cov=src", "--cov-report=html", "--cov-report=json:.coverage.json"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["src/conlanger/ml/models/*", "src/conlanger/ml/utils.py"]

[tool.coverage.report]
fail_under = 95
skip_empty = true
exclude_also = ["def display_rows\\("]

[dependency-groups]
dev = [
    "lxml>=6.0.2",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.1",
    "strip-ansi>=0.1.1",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
# explicit = true

[tool.ruff]
exclude = ["*.ipynb", "legacy/*", ".scratch/*"]

[tool.ruff.format]
exclude = ["*.ipynb", "legacy/*", ".scratch/*"]
