rules:
        - rule:
                  id: Blackfoot-nr
                  content: "nl → s"
                  reason: "Corrected from original source: International Journal of American Linguistics, Vol. 55, No. 1, p 50"
        - rule:
                  id: Blackfoot-ʔθ,ʔr
                  content: "ʔθ, ʔr → {ʔ,j,∅}"
                  reason: "Corrected from original source: International Journal of American Linguistics, Vol. 55, No. 1, p 50"
        - rule:
                  id: Dena’ina-ʃʷ,x-z,ʒʷ,ɣ
                  content: "{ʃ(ʷ),x} {z,ʒ(ʷ),ɣ} → s j"
                  reason: "Corrected from original source: Northern Athapaskan Languages (Vol. 6), p. 73"
        - rule:
                  id: Old-Irish-m̩-n̩
                  content: "m̩ n̩ → am an / _{s,({m,j,w})V}"
                  reason: "Bracket fix for env set with optional grouping"
        - rule:
                  id: Spanish-—-Vdz
                  content: "— Vdz → ∅ / {nts,ndz,rdz}_"
                  reason: "Bracket fix - not confirmed from original source"
        - rule:
                  id: Seneca-r_3
                  content: "r → j / C[-glottal](h)_{o(ː),õ(ː)}"
                  reason: "Bracket fix - not confirmed from original source"
        - rule:
                  id: Seneca-ẽː
                  content: "ẽ(ː) → e(ː) / _{e(ː),o(ː)}"
                  reason: "Bracket fix - not confirmed from original source"
        - rule:
                  id: Zayse-Zergulla-x3
                  content: "x₂ → ɡ / V_#"
                  reason: "x3 does not appear in the original source, x2 is a best guess"
        - rule:
                  id: Proto-Dravidian-s_3
                  content: "s → ∅ / #V_{r,ɾ,l}"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Proto-Dravidian-r̀
                  content: "{r,ɾ} → r"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Proto-Dravidian-ŕ
                  content: "{ɹ,ɾ} → r / V_V"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Proto-Dravidian-n-nː-rn
                  content: "n nː rn → {n,r} n(ː) ɳ / V_V"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Proto-Dravidian-nː
                  content: "nː → n(ː)"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Proto-Dravidian-nr̀
                  content: "n{r,ɾ} → nr"
                  reason: "Replacing with IPA symbols"
        - rule:
                  id: Yemsa-kʼ
                  content: "kʼ → k / #_, _#"
                  reason: "This is a guess, it could be _# or _,#"
        - rule:
                  id: Proto-Mongolic-tʃ_2
                  content: "tʃ → d / #_, _#"
                  reason: "This is a guess, it could be _# or _,#"
        - rule:
                  id: Old-Japanese-Vowel-Shift-u,ɨi-,a,i-ɨi,ia,ə-uɨ,a,ə
                  content: "{u,ɨ}i {a,ə}i i{a,ə} u{ɨ,a,ə} → wi e je wo"
                  reason: "Corrected from original source: https://conf.ling.cornell.edu/whitman/FrellWhitman.pdf"
        - rule:
                  id: Old-Provençal-rdʒ
                  content: "rdʒ → {rdʒ,rz}"
                  reason: "Skipping intermediate step"
        - rule:
                  id: Old-Provençal-rtVɡ
                  content: "rtVɡ → {rdʒ,rs}"
                  reason: "Skipping intermediate step"
        - rule:
                  id: Old-Provençal-rtʃ-rdtʃ
                  content: "rtʃ rdtʃ → {rts,rs} {rz,rts,rdʒ}"
                  reason: "Skipping intermediate step"
        - rule:
                  id: Proto-North-Sarawak-ə_3
                  content: "ə → ∅ / VC_CV"
                  reason: "Adding env delimiter"
        - rule:
                  id: Quito-χ
                  content: "χ → h / #_"
                  reason: "Adding env delimiter"
        - rule:
                  id: Riobamba-χ
                  content: "χ → kʰ / #_"
                  reason: "Adding env delimiter"
        - rule:
                  id: Romanian-a
                  content: "a → ɨ / _N ! _{nː,mn}"
                  reason: "Adding env delimiter"
        - rule:
                  id: Old-English-i,u
                  content: "{i,u} → ∅ / _# ! V[-long]C_#"
                  reason: "Correcting env delimiter"
        - rule:
                  id: Comox-ʔ
                  content: "ʔ → ∅ / V₃R_V"
                  reason: "Adding env delimiter"
        - rule:
                  id: Portuguese-V_3
                  content: "V → ∅ / ”V%s_t(C)V(C)# ; (irregular)"
                  reason: "Adding env delimiter"
        - rule:
                  id: Proto-Dhegiha-k_2
                  content: "k → ∅ / #t_ ; (in morphemes)"
                  reason: "Adding env delimiter"
        - rule:
                  id: Latin-l
                  content: "l → r / _Vl"
                  reason: "Correcting env delimiter"
        - rule:
                  id: Eritai-∅
                  content: "∅ → dz / î_V"
                  reason: "Adding env delimiter"
        - rule:
                  id: Old-Russian-kt-ɡd
                  content: "kt → ɡd / _E"
                  reason: "Correcting delimiters - this may be wrong"
        - rule:
                  id: Attic-Greek-ɔ
                  content: "ɔ → ∅ / %i_n#, %i_s#"
                  reason: "Correcting env - this may be wrong"
        - rule:
                  id: Proto-Circassian-ɡʲʷ-xʲʷ-ɣʲʷ?
                  content: "ɡʲʷ xʲʷ ɣʲʷ → ɡʷ xʷ ʁʷ"
                  reason: "Removing (?) - this may be wrong"
        - rule:
                  id: Proto-Erromango-r
                  content: "r → L / sporadic"
                  reason: "Corrected from original source: https://www.ethnologue.com/language/erohttps://www.researchgate.net/publication/306887303_The_Linguistic_History_of_Southern_Vanuatu"
        - rule:
                  id: Proto-Erromango-v_2
                  content: "v → f / [+ sibilant](..)$(..)_"
                  reason: "Corrected from original source: https://www.ethnologue.com/language/erohttps://www.researchgate.net/publication/306887303_The_Linguistic_History_of_Southern_Vanuatu"
        - rule:
                  id: Proto-Erromango-v_3
                  content: "v → f / _(..)$(..)[+ sibilant]"
                  reason: "Corrected from original source: https://www.ethnologue.com/language/erohttps://www.researchgate.net/publication/306887303_The_Linguistic_History_of_Southern_Vanuatu"
        - rule:
                  id: Early-Icelandic-O
                  content: "O[α PLACE] → ∅ / {F[- α PLACE],r,l}_O"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Early-Icelandic-S
                  content: "S[α PLACE] → ∅ / N[α PLACE]_S"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Egyptian-Arabic-i,u
                  content: "{i,u}[-stress, -long] → ∅ / VC_CV"
                  reason: "Replacing prose"
        - rule:
                  id: Moroccan-Arabic-a,i
                  content: "{a,i}[-long] → ə / _"
                  reason: "Replacing prose"
        - rule:
                  id: Moroccan-Arabic-u
                  content: "u[-long] → ə / _"
                  reason: "Replacing prose"
        - rule:
                  id: Moroccan-Arabic-u_2
                  content: "u[-long] → ʊ / _"
                  reason: "Replacing prose"
        - rule:
                  id: Proto-Slavic-bʱ-dʱ-ɡʱ,ɡ́ʱ-ɡʷʱ
                  content: "bʱ dʱ ɡʱ ɡʷʱ → b d ɡ ɡʷ"
                  reason: "Not really sure what to do with ɡ́"
        - rule:
                  id: Proto-Slavic-Kʷ-ḱ-ɡ́
                  content: "Kʷ ḱ g → K s z"
                  reason: "Not really sure what to do with ɡ́"
        - rule:
                  id: Saigon-Vietnamese-ə
                  content: "ə → ∅ / {i,ɨ}_{p,m,w}"
                  reason: "Typo? - ə → ∅ / {i,ɨ}_{p,m.w}"
        - rule:
                  id: Blackfoot-ket
                  content: "ket → {tː, sː}"
                  reason: "Allowing for possible alternative output"
        - rule:
                  id: Cheyenne-W
                  content: "W → ∅ / [+nasal]_, _[+nasal], t_, _t"
                  reason: "Prose"
        - rule:
                  id: Old-Provençal-p-k-tʃ-b-ɡ-β-j
                  content: "p k tʃ b ɡ β j → b ɡ i {b,i} ∅ {u,i} i / _r"
                  reason: |
                          Removing intermediate steps - original:
                          p k tʃ b ɡ β j → b ɡ i {b,u,u→y→i} ∅ {u,u→y→i} i / _r
        - rule:
                  id: Asaro-N
                  content: "N → [α PLACE] / _S[α PLACE]"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Auyana-N
                  content: "N → [α PLACE] / _C[α PLACE]"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Gadsup-N_2
                  content: "N → [α PLACE] / _C[α PLACE]"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Basque-N
                  content: "N → [α PLACE] / _C[α PLACE]"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Kuskokwim-Yup’ik-F+voice_2
                  content: "F[+voice, α PLACE] → S[α PLACE] / l̥_"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: Vowel-Shifts_2-N-glottalized
                  content: "N[-place, α PLACE] → e / _O[α PLACE] ; “‘in primary forms’” "
                  reason: "I think this is probably wrong"
        - rule:
                  id: Sebirwa-NC_2
                  content: "NC[α PLACE] → N[α PLACE]C / #_ ; sporadic (in verbs)"
                  reason: "Bit of a guess"
        - rule:
                  id: Aquitanian-N
                  content: "N → [α PLACE] / _S[α PLACE]"
                  reason: "Using asca syntax - unsure how else to represent POA"
        - rule:
                  id: American-English-æ
                  content: "æ → {æː,ɑː} / _{F[-voiced],N[-voiced]} ; (“words which change vary between dialects”)"
                  reason: "Prose"
        - rule:
                  id: Biblical-Hebrew-p-b-t-d-k-ɡ
                  content: "p b t d k ɡ → b v θ ð x ɣ / sporadic ; non-intial singletons"
                  reason: |
                          The source doesn't seem to clarify anything for me:
                          https://www.adath-shalom.ca/history_of_hebrew.htm
        - rule:
                  id: Spanish-—-e
                  content: "e → i / _Cj ! _p ; C = p"
                  reason: "Variable value for C"
        - rule:
                  id: Proto-Boreafrasian-z
                  content: "z → d / sporadic ; “when another sibilant is in the word nearby” and (word-finally?) when “noun-stem final”"
                  reason: "Too complex to parse"
        - rule:
                  id: Arapaho-C,#Vʔ
                  content: "{Vʔ,ʔ} → {Vː∅,∅} / #_C, C_C, _C"
                  reason: |
                          TODO: resolve this one properly.
                          Original rule: ({C,#}V)ʔ → ({C,#}Vː)∅ / _C
                          The source says: 
                                  "*? is lost before a true consonant, with compensatory 
                                  lengthening of a preceding nonpostvocal"
                          I think it may be necessary to split this into multiple rules.
        - rule:
                  id: Gros-Ventre-C,#V-longʔ
                  content: "{V[-long]ʔ,ʔ} → {V[+falling tone]∅,∅} / #_C, C_C, _C"
                  reason: |
                          TODO: resolve this one properly.
                          Original rule: ({C,#}V[-long])ʔ → ({C,#}Vː[+falling tone])∅ / _C
        - rule:
                  id: Shetland-Norn-ɒ_2
                  content: "ɒ → ø / _O[+dental], _O[+alveolar]"
                  reason: |
                          Handling alternatives in distinctive feature
                          ɒ → ø / _O[+ dental/alveolar]
        - rule:
                  id: Shetland-Norn-a
                  content: "a → ∅ / C[+dental]_u, C[+alveolar]_u"
                  reason: |
                          Handling alternatives in distinctive feature
                          a → ∅ / C[+ dental/alveolar]_u
        - rule:
                  id: Shetland-Norn-yː
                  content: "yː → ø / _O[+dental], _O[+alveolar]"
                  reason: |
                          Handling alternatives in distinctive feature
                          yː → ø / _O[+ dental/alveolar]
        - rule:
                  id: Anglo-Frisian-a
                  content: "a[-long] → ɑ̃ / _N"
                  reason: "a → ɑ̃ / _N (short only)"
        - rule:
                  id: Anglo-Frisian-aː
                  content: "a[+long, -nasal] → æ[+long, -nasal] / ! _N"
                  reason: "aː → æː / ! _N or if nasalized"
        - rule:
                  id: Anglo-Frisian-i,u
                  content: "{i,u} → ∅ / _# ! VC_"
                  reason: "Typo? - {i,u} → ∅ / -# ! VC_"
        - rule:
                  id: Proto-Southern-Athabaskan-K
                  content: "K → ts"
                  reason: |
                          Hoijer (1938) §29.1.1.1.19: velar K becomes dental TS series.
                          IPA affricate /ts/ avoids per-letter T/S group expansion (P:[-voice]P).
