- from: " / (unless|when not) "
  to: " / ! "
  use_regex: True
  reason: replace prose
- from: ATR
  to: atr
  reason: Lowercase feature name
- from: RTR
  to: rtr
  reason: Lowercase feature name
- from: (h → ɦ?)
  to: ""
  reason: remove ambuguous text
- from: " ʰS "
  to: " Sʰ "
  reason: typo?

#region align positional text
- from: " / near ħ ʕ"
  to: " / near {ħ,ʕ}"
- from: " / if s or z occur "
  to: " / near {s,z} ; if s or z occur "
- from: " next to "
  to: " adjacent to "
- from: " / syllable-initially"
  to: " / $_ "
# - from: " / (_[\\w]+) \\(possibly only (word-)?initially\\??\\)"
#   to: " / #\\1, \\1" # TODO: how to handle alternative, optional envs?
#   use_regex: True
- from: " / if ɑ(ː) is elsewhere in the word"
  to: " / near ɑ(ː) ; if ɑ(ː) is elsewhere in the word"
- from: " æ(ː) / else (sometimes it seems more like ɛ(ː) to me)"
  to: " {æ(ː),ɛ(ː)} / else"
- from: " / in coda"
  to: " / :{ _#, _% }: ; in coda" # TODO: this is a hack to handle coda envs
- from: "_ or when _"
  to: "_, _"
- from: "_ or _"
  to: "_, _"
- from: " / intertonic"
  to: " / %[+str]_%[+str]" # TODO: needs confirmation
#endregion

#region dialect text cleanup
- targets:
    - " in (Mentasta Ahtna)"
    - " in ((West|East) Swampy Cree)"
    - " in (Nelemwa)"
    - " (Pije and Fwai)"
    - " in (Ware Sekani)"
    - " in (Queensland( and New South Wales)?)"
    # - " \\(in (Languedoc)\\)"|varieties
  to: " in \\1 dialects"
  use_regex: True

# TODO: need to handle singular cases without breaking other rules
- from: "(dialects|regions|varieties)( (or|and) (dialects|regions|varieties))*"
  to: "dialects"
  use_regex: True

- from: "in(?: the)?( some| most| all| many)?( [a-zA-Z]+)?( and [a-zA-Z]+)* dialects"
  to: "in\\1\\2\\3 dialects"
  use_regex: True
#endregion

#region feature and class letter replacements
- from: " (/|!) (near|adjacent to) a vowel"
  to: " \\1 \\2 V"
  use_regex: True
- from: " (/|!) (near|adjacent to) (another consonant|consonants)"
  to: " \\1 \\2 C"
  use_regex: True
- from: " (/|!) (near|adjacent to) nasals"
  to: " \\1 \\2 N"
  use_regex: True
- from: " (/|!) (near|adjacent to) a nasal vowel"
  to: " \\1 \\2 V[+nasal]"
  use_regex: True
- from: " (/|!) (near|adjacent to) gutturals"
  to: " \\1 \\2 [+laryngeal]"
  use_regex: True
- from: " (/|!) (near|adjacent to) emphatics"
  to: " \\1 \\2 [+emphatic]"
  use_regex: True
- from: " / unstressed"
  to: " / [-stress]"
- from: " / stressed"
  to: " / [+stress]"
- from: " / if short and unstressed"
  to: " / [-long, -stress]"
- from: " / _Ra (short a only), "
  to: " / _Ra[-long] ; "
- from: C[+ affricate]
  to: A
- from: "high(er)"
  to: "hi"
- from: + A POA
  to: α place
  reason: Point of articulation - asca syntax alpha notation
- from: + B POA
  to: β place
  reason: Point of articulation - asca syntax alpha notation
- from: "[anything]"
  to: "[]"
  reason: Use asca syntax for a wildcard symbol
#endregion

- from: " \\(→ (\\w+) dialectally\\?\\)"
  to: " → \\1 ; dialectal"
  use_regex: True
  reason: dialectal
- from: \(dialectally → (\w+)\?\)
  to: → \1 ; dialectal
  use_regex: True
  reason: dialectal
- from: \(→ (\w+) ?\??\)
  to: → \1
  use_regex: True
  reason: chaining
- from: \((\w)\?\)
  to: (\1)
  use_regex: True
  reason: optional
- from: (\([^)]+ is rare\))
  to: ; \1
  use_regex: True
  reason: comment
- from: → (?)
  to: ""
  reason: unknown output
- from: bw mw → ɡw ŋw (→ ɡ ŋ / _V[+ rounded])
  to: bw mw → ɡw ŋw → ɡ ŋ / _V[+ rounded]
  reason: chaining
- from: nd ld (→ nː lː ?)
  to: nd ld → nː lː
  reason: chaining
- from: ɣ → q (more likely, *ɢ → q instead of → ɣ)
  to: ɣ → q ; (more likely, *ɢ → q instead of → ɣ)
  reason: comment
- from: " (/|!) at word boundaries"
  to: " \\1 #_, _#"
  use_regex: True
  reason: replace prose

#region adjacent replacements
# - from: " (/|!) adjacent to ([A-Z])"
#   to: " \\1  \\2_, _\\2"
#   use_regex: True
#   reason: replace prose
# - from: " (/|!) adjacent to (\\{[^}]+\\})"
#   to: " \\1  \\2_, _\\2"
#   use_regex: True
# - from: " (/|!) adjacent to (\\w?\\[[^]]+\\])"
#   to: " \\1  \\2_, _\\2"
#   use_regex: True
#   reason: replace prose
#endregion

#region near replacements
- from: " (/|!) near ([A-Z])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) near (\\{[^}]+\\})"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) near (\\w?\\[[^]]+\\])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) near (\\w?\\([^)]+\\))"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
#endregion

#region sporadic - TODO: change this to attach to the environment
- from: " (/|!) in ([\\w ]+) dialects"
  to: " \\1 dialectal ; in \\2 dialects"
  use_regex: True

- targets:
    - " / (in certain situations)"
    - " (in certain frequently-used words)"
    - " / (“in some positions”)"
    - " / (except in several)"
    - " / (depending on the environment)"
    - " / (\\(“when in unstressed penult)"
    - " / (some sequences)"
    - " / (sometimes)"
    - " / (in Form VI)"
    - " / (“\\[b\\]etween the last two vowels of a proparoxytone”)"
    - ", (except in certain)"
    - ", (in the feminine ending)"
  to: " / sporadic ; \\1"
  use_regex: True
  reason: sporadic environment

- from: " (in southern dialects"
  to: " sporadic ; (in southern dialects"
- from: " (in some dialects"
  to: " sporadic ; (in some dialects"
- from: " (some dialects"
  to: " sporadic ; (some dialects"
- from: " (most dialects"
  to: " ; (most dialects"
- from: " / except when CV_V in U"
  to: " / sporadic ! CV_V ; except when CV_V in U"
- from: " / in prefixes related to"
  to: " sporadic ; / in prefixes related to"
  reason: unhandled positional environment
# - from: " ! in Ware Sekani"
#   to: " sporadic ; not in Ware Sekani"
# - from: " ! in Queensland"
#   to: " sporadic ; not in Queensland"
- from: " (some exceptions"
  to: " ; sporadic (some exceptions"
- from: " for some C"
  to: " ; sporadic ; for some C"
- from: " (rare) ! form of "
  to: " / sporadic ; (rare) ! form of "
- from: " / ! if one of the above"
  to: " / sporadic ; ! if one of the above"
- from: " yj (→ yː sometimes)"
  to: "{yj,yː}"
- from: " (→ i in most descendants"
  to: " → i / sporadic ; (→ i in most descendants"
  reason: workaround - we can't handle different envs for chained rules
- from: " (conditioning unclear)"
  to: " / sporadic ; (conditioning unclear)"
- from: " / if ʃ is somewhere"
  to: " / sporadic ; if ʃ is somewhere"
  reason: interim non-local co-occurrence env until issue 122 structured conditioning
- from: " / if ʒ is somewhere"
  to: " / sporadic ; if ʒ is somewhere"
  reason: interim non-local co-occurrence env until issue 122 structured conditioning
- from: (kʷ → ɡʷ → ɡ ?)
  to: kʷ → ɡʷ → ɡ / sporadic ; (kʷ → ɡʷ → ɡ ?)
  reason: workaround
- from: " / in two cases cited"
  to: " / sporadic ; in two cases cited"
- from: " / in some "
  to: " / sporadic ; in some "
- from: " / in diminutives"
  to: " / sporadic ; diminutives"
  reason: unhandled positional environment
- from: " / in nominal suffixes"
  to: " / sporadic ; nominal suffixes"
  reason: unhandled positional environment
- from: " / in nouns"
  to: " / sporadic ; in nouns"
  reason: unhandled positional environment
- from: ", in some words"
  to: " sporadic ; in some words"
- from: " / in “"
  to: " / sporadic ; in “"
- from: " / possible exception"
  to: " / sporadic ; possible exception"
- from: " / unclear conditioning"
  to: " / sporadic ; unclear conditioning"
- from: " (except in the"
  to: " / sporadic ; (except in the"
- from: "“under to [sic] the influence of neighboring consonants”"
  to: "/ sporadic ; “under to [sic] the influence of neighboring consonants”"
- from: ", in monosyllables"
  to: " / sporadic ; in monosyllables"
- from: " / in monosyllables"
  to: " / sporadic ; in monosyllables"
- from: " / pretonic"
  to: " / sporadic ; pretonic"
  reason: unhandled positional environment
- from: " / posttonic"
  to: " / sporadic ; posttonic"
  reason: unhandled positional environment
- from: " if {M,Vː} " # TODO: change this to handle "previously in the word" or similar
  to: " / sporadic ; if {M,Vː} "
  reason: unhandled positional environment
- from: " ! some monosyllables"
  to: " ; sporadic ! some monosyllables"
- from: ", often"
  to: " ; sporadic - often"
#endregion

#region comment handling
- targets:
    - " (Do not necessarily"
    - " (remains "
    - " (“[a]rchaic relic”)"
    - " (again, "
    - " (Blevins "
    - " (Whimemsz "
    - " (first change marked "
    - " (not sure what "
    - " “(before a prefix; "
    - " (note that "
    - " (?; included here based on "
    - " (at least one instance of "
    - " (velar fricative is conjectured"
    - " (fricative changes to approximant)"
    - " (→ b seems more common)"
    - " (specifically"
    - " (*)"
    - " “("
    - " (“"
    - " (seems to "
    - " (this second one"
  comment: true
- from: "#, though "
  to: "# ; though "
- from: " / plain t only"
  to: " ; plain t only"
#endregion

#region TBD
- from: ", in polysyllables"
  to: " ; in polysyllables"
- from: "# in polysyllables"
  to: "# ; in polysyllables"
- from: ", in Milyan"
  to: " ; , in Milyan"
  reason: comment
- from: ", also in proclitics"
  to: " ; , also in proclitics"
- from: " / in open syllables "
  to: " ; in open syllables "
  reason: unhandled environment
#endregion

# these are wrong
# - from: " / when stem-final"
#   to: " / _%# ; when stem-final"
#   reason: unhandled positional environment
# - from: " / when-stem final"
#   to: " / _%# ; when-stem final"
#   reason: unhandled positional environment
# - from: "k ʃk → k* kː / V_V "
#   to: "ʃk → kː / V_V ; k ʃk → k* kː / V_V "
#   reason: unresolvable symbol

# keep these last because they are so broad
- from: " / in "
  to: " / "
  reason: replace prose
- from: " ! in "
  to: " ! "
  reason: replace prose
- from: ", in "
  to: " ; sporadic - in "
  reason: replace prose
# - from: " “("
#   to: " ; “("
#   reason: comment
# - from: " (“"
#   to: " ; (“"
#   reason: comment
