- from: " / (unless|when not) "
  to: " / ! "
  use_regex: True
  reason: replace prose
- from: " / near ħ ʕ"
  to: " / near {ħ,ʕ}"
  reason: convert to set notation

#region dialect text cleanup
- targets:
    - " in (Mentasta Ahtna)"
    - " in (West Swampy Cree)"
    - " in (Nelemwa)"
    - " (Pije and Fwai)"
    - " in (Ware Sekani)"
    - " in (Queensland and New South Wales)"
    # - " \\(in (Languedoc)\\)"
  to: " in \\1 dialects"
  use_regex: True
  reason: dialect text

- from: "(dialects|regions|varieties)( (or|and) (dialects|regions|varieties))*"
  to: "dialects"
  use_regex: True
  reason: align dialect text

- from: "in( some| most| all| many)?( [a-zA-Z]+)?( and [a-zA-Z]+)* dialects"
  to: "in\\1\\2\\3 dialects"
  use_regex: True
  reason: align dialect text
#endregion

#region class letter replacements
- from: " (/|!) (near|adjacent to) a vowel"
  to: " \\1 \\2 V"
  use_regex: True
  reason: replace prose

- from: " (/|!) (near|adjacent to) (another consonant|consonants)"
  to: " \\1 \\2 C"
  use_regex: True
  reason: replace prose
- from: " (/|!) (near|adjacent to) nasals"
  to: " \\1 \\2 N"
  use_regex: True
  reason: replace prose
- from: " (/|!) (near|adjacent to) a nasal vowel"
  to: " \\1 \\2 V[+nasal]"
  use_regex: True
  reason: replace prose
#endregion

#region feature replacements
- from: " (/|!) (near|adjacent to) gutturals"
  to: " \\1 \\2 [+laryngeal]"
  use_regex: True
  reason: replace prose
- from: " (/|!) (near|adjacent to) emphatics"
  to: " \\1 \\2 [+emphatic]"
  use_regex: True
  reason: replace prose
- from: " / unstressed"
  to: " / [-stress]"
  reason: replace prose
- from: " / stressed"
  to: " / [+stress]"
  reason: replace prose
#endregion

- from: " \\(→ (\\w+) dialectally\\?\\)"
  to: " → \\1 ; dialectal"
  use_regex: True
  reason: dialectal
- from: \(dialectally → (\w+)\?\)
  to: → \1 ; dialectal
  use_regex: True
  reason: dialectal
- from: \(→ (\w+) ?\??\)
  to: → \1
  use_regex: True
  reason: chaining
- from: \((\w)\?\)
  to: (\1)
  use_regex: True
  reason: optional
- from: (\([^)]+ is rare\))
  to: ; \1
  use_regex: True
  reason: comment
- from: → (?)
  to: ""
  reason: unknown output
- from: bw mw → ɡw ŋw (→ ɡ ŋ / _V[+ rounded])
  to: bw mw → ɡw ŋw → ɡ ŋ / _V[+ rounded]
  reason: chaining
- from: nd ld (→ nː lː ?)
  to: nd ld → nː lː
  reason: chaining
- from: ɣ → q (more likely, *ɢ → q instead of → ɣ)
  to: ɣ → q ; (more likely, *ɢ → q instead of → ɣ)
  reason: comment
- from: " (/|!) at word boundaries"
  to: " \\1 #_, _#"
  use_regex: True
  reason: replace prose

#region adjacent replacements
- from: " (/|!) adjacent to ([A-Z])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) adjacent to (\\{[^}]+\\})"
  to: " \\1  \\2_, _\\2"
  use_regex: True
- from: " (/|!) adjacent to (\\w?\\[[^]]+\\])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
#endregion

#region near replacements
- from: " (/|!) near ([A-Z])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) near (\\{[^}]+\\})"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
- from: " (/|!) near (\\w?\\[[^]]+\\])"
  to: " \\1  \\2_, _\\2"
  use_regex: True
  reason: replace prose
#endregion

# - from: " (/|!) near ([A-Z])"
#   to: " \\1 \\2_, _\\2"
#   use_regex: True
#   reason: replace prose
# - from: " / near nasals"
#   to: " / _,N ;"
#   reason: replace prose

- from: " / in ([\\w ]+) dialects"
  to: " / sporadic ; in \\1 dialects"
  use_regex: True
  reason: dialect text
- targets:
    - " / (in certain situations)"
    - " (in certain frequently-used words)"
    - ", (except in certain)"
    - " / (“in some positions”)"
    - " / (except in several)"
    - ", (in the feminine ending)"
    - " / (depending on the environment)"
    - " / (\\(“when in unstressed penult)"
    - " / (some sequences)"
    - " / (sometimes)"
    - " / (in Form VI)"
    - " / (“\\[b\\]etween the last two vowels of a proparoxytone”)"
  to: " / sporadic ; \\1"
  use_regex: True
  reason: sporadic environment

- from: " (in southern dialects"
  to: " sporadic ; (in southern dialects"
  reason: replace prose
- from: " (in some dialects"
  to: " sporadic ; (in some dialects"
  reason: replace prose
- from: " (some dialects"
  to: " sporadic ; (some dialects"
  reason: replace prose
- from: " (most dialects"
  to: " ; (most dialects"
  reason: replace prose
- from: " / except when CV_V in U"
  to: " / sporadic ! CV_V ; except when CV_V in U"
  reason: replace prose
- from: " / in prefixes related to"
  to: " sporadic ; / in prefixes related to"
  reason: unhandled positional environment
- from: " ! in Ware Sekani"
  to: " sporadic ; not in Ware Sekani"
  reason: replace prose
- from: " ! in Queensland"
  to: " sporadic ; not in Queensland"
  reason: replace prose
- from: " (some exceptions"
  to: " ; sporadic (some exceptions"
  reason: replace prose
- from: " / _Ra (short a only), "
  to: " / _Ra[-long] ; sporadic ; "
  reason: replace prose
- from: " for some C"
  to: " ; sporadic ; for some C"
  reason: replace prose
- from: " (rare) ! form of "
  to: " / sporadic ; (rare) ! form of "
  reason: replace prose
- from: " / ! if one of the above"
  to: " / sporadic ; ! if one of the above"
  reason: replace prose
- from: There seems to ahve been some stuff going on
  to: " ; There seems to ahve been some stuff going on"
- targets:
    - " (Do not necessarily"
    - " (remains "
    - " (“[a]rchaic relic”)"
    - " (again, "
    - " (Blevins "
    - " (Whimemsz "
    - " (first change marked "
    - " (not sure what "
    - " “(before a prefix; "
    - " (note that "
    - " (?; included here based on "
    - " (at least one instance of "
    - " (velar fricative is conjectured"
    - " (fricative changes to approximant)"
  comment: true
# these are wrong
# - from: " / when stem-final"
#   to: " / _%# ; when stem-final"
#   reason: unhandled positional environment
# - from: " / when-stem final"
#   to: " / _%# ; when-stem final"
#   reason: unhandled positional environment
- from: " (→ yː sometimes)"
  to: " → yː / sporadic ; (→ yː sometimes)"
  reason: workaround - we can't handle different envs for chained rules
- from: " (→ i in most descendants"
  to: " → i / sporadic ; (→ i in most descendants"
  reason: workaround - we can't handle different envs for chained rules
- from: " (conditioning unclear)"
  to: " / sporadic ; (conditioning unclear)"
  reason: replace prose
- from: " / syllable-initially (h → ɦ?)"
  to: " / $_ ; (h → ɦ?)"
  reason: replace prose
- from: " / syllable-initially"
  to: " / $_ "
  reason: "replace "
- from: " / if s or z occur"
  to: " / sporadic ; if s or z occur"
  reason: interim non-local co-occurrence env until issue 122 structured conditioning
- from: " / if ʃ is somewhere"
  to: " / sporadic ; if ʃ is somewhere"
  reason: interim non-local co-occurrence env until issue 122 structured conditioning
- from: " / if ʒ is somewhere"
  to: " / sporadic ; if ʒ is somewhere"
  reason: interim non-local co-occurrence env until issue 122 structured conditioning
- from: " / if short and unstressed"
  to: " / [-long, -stress]"
  reason: replace prose
- from: "k ʃk → k* kː / V_V "
  to: "ʃk → kː / V_V ; k ʃk → k* kː / V_V "
  reason: unresolvable symbol
- from: " (→ b seems more common)"
  to: " ; (→ b seems more common)"
  reason: replace prose
- from: (kʷ → ɡʷ → ɡ ?)
  to: kʷ → ɡʷ → ɡ / sporadic ; (kʷ → ɡʷ → ɡ ?)
  reason: workaround
- from: C[+ affricate]
  to: O[+delrel]
  reason: asca syntax replacement
- from: " ʰS "
  to: " Sʰ "
  reason:
    I have no idea what ʰS is supposed to represent - I'm assuming it's a typo
    for Sʰ
- from: + A POA
  to: α place
  reason: Point of articulation - asca syntax alpha notation
- from: + B POA
  to: β place
  reason: Point of articulation - asca syntax alpha notation
- from: ATR
  to: atr
  reason: Lowercase feature name
- from: RTR
  to: rtr
  reason: Lowercase feature name
- from: " / in two cases cited"
  to: " / sporadic ; in two cases cited"
  reason: replace prose
- from: " / in some "
  to: " / sporadic ; in some "
  reason: replace prose
- from: " / in diminutives"
  to: " / sporadic ; diminutives"
  reason: unhandled positional environment
- from: " / in nominal suffixes"
  to: " / sporadic ; nominal suffixes"
  reason: unhandled positional environment
- from: " / in nouns"
  to: " / sporadic ; in nouns"
  reason: unhandled positional environment
- from: ", in some words"
  to: " sporadic ; in some words"
  reason: replace prose
- from: ", in polysyllables"
  to: " ; in polysyllables"
  reason: replace prose
- from: "# in polysyllables"
  to: "# ; in polysyllables"
  reason: replace prose
- from: " / in “"
  to: " / sporadic ; in “"
  reason: replace prose
- from: " / in coda"
  to: " / :{ _#, _% }: ; in coda"
  reason: unhandled positional environment
- from: " / possible exception"
  to: " / sporadic ; possible exception"
  reason: replace prose
- from: " / unclear conditioning"
  to: " / sporadic ; unclear conditioning"
  reason: replace prose
- from: " (seems to be a sporadic change"
  to: " ; (seems to be a sporadic change"
- from: " (except in the"
  to: " / sporadic ; (except in the"
  reason: replace prose
- from: ", in Milyan"
  to: " ; , in Milyan"
  reason: comment
- from: " (*)"
  to: " ; (*)"
  reason: ambiguous symbol
- from: "[anything]"
  to: "[]"
  reason: Use asca syntax for a wildcard symbol
- from: "_ or when _"
  to: "_,_"
  reason: replace prose
- from: "“under to [sic] the influence of neighboring consonants”"
  to: "/ sporadic ; “under to [sic] the influence of neighboring consonants”"
  reason: replace prose
- from: ", often"
  to: " ; , often"
  reason: replace prose
- from: "high(er)"
  to: "hi"
  reason: ambiguous feature name
- from: " / intertonic"
  to: " / %[+str]_%[+str]"
  reason: replace prose
- from: " / plain t only"
  to: " ; plain t only"
  reason: replace prose
- from: " ! some monosyllables"
  to: " ; sporadic ! some monosyllables"
  reason: replace prose
- from: ", in monosyllables"
  to: " / sporadic ; in monosyllables"
  reason: replace prose
- from: " / in monosyllables"
  to: " / sporadic ; in monosyllables"
  reason: replace prose
- from: ", also in proclitics"
  to: " ; , also in proclitics"
  reason: replace prose
- from: "#, though "
  to: "# ; , though "
  reason: comment
- from: " / pretonic"
  to: " / sporadic ; pretonic"
  reason: unhandled positional environment
- from: " / posttonic"
  to: " / sporadic ; posttonic"
  reason: unhandled positional environment
- from: " if {M,Vː} "
  to: " / sporadic ; if {M,Vː} "
  reason: unhandled positional environment
- from: " (this second one"
  to: " ; (this second one"
  reason: replace prose
- from: " / in open syllables "
  to: " ; in open syllables "
  reason: unhandled environment

# keep these last because they are so broad
- from: " / in "
  to: " / "
  reason: replace prose
- from: " ! in "
  to: " ! "
  reason: replace prose
- from: ", in "
  to: " ; sporadic - in "
  reason: replace prose
- from: " “("
  to: " ; “("
  reason: comment
- from: " (“"
  to: " ; (“"
  reason: comment
