- from:
    “The PIE rules for the voicing of s → z, as in [nizdos] for *nisdos, are assumed
    to apply”
  to: s → z / C[+voice]_
  reason: "*nisdos > nizdos"
- from: “In contrast, Romanian exhibits
  to: ; “In contrast, Romanian exhibits
  reason: comment
- from: ew (→ øj) → yj
  to: ew → øj → yj
  reason: chaining
- from: (→ ʕ)
  to: → ʕ
  reason: chaining
- from: bw mw → ɡw ŋw (→ ɡ ŋ / _V[+ rounded])
  to: bw mw → ɡw ŋw → ɡ ŋ / _V[+ rounded]
  reason: chaining
- from: "q (→ kw ?) → v "
  to: "q → kw → v "
  reason: chaining
- from: w (→ v?) → f
  to: w → v → f
  reason: chaining
- from: ɛː → ɛi (→ əi?)
  to: ɛː → ɛi → əi
  reason: chaining
- from: a → ɒ? (→ o)
  to: a → ɒ → o
  reason: chaining
- from: nd ld (→ nː lː ?)
  to: nd ld → nː lː
  reason: chaining
- from: ɣ → q (more likely, *ɢ → q instead of → ɣ)
  to: ɣ → q ; (more likely, *ɢ → q instead of → ɣ)
  reason: comment
- from: " / at word boundaries"
  to: " / #_, _#"
  reason: replace prose
- from: " ! at word boundaries"
  to: " ! #_, _#"
  reason: replace prose
- from: " / unstressed"
  to: " / [-stress]"
  reason: replace prose
- from: " / stressed"
  to: " / [+stress]"
  reason: replace prose
- from: " / adjacent to short u"
  to: " / u[-long]_, _u[-long]"
  reason: replace prose
- from: " / unless adjacent to another consonant"
  to: " / ! C_,_C ; unless adjacent to another consonant"
  reason: replace prose
- from: " / adjacent to {"
  to: " / _,{"
  reason: replace prose
- from: " ! adjacent to {"
  to: " ! _,{"
  reason: replace prose
- from: " / adjacent to a vowel"
  to: " / V_, _V ; adjacent to a vowel"
  reason: replace prose
- from: " / near emphatics"
  to: " / _[+ emphatic], [+ emphatic]_ ; near emphatics"
  reason: replace prose
- from: " / near consonants"
  to: " / C_, _C ; near consonants"
  reason: replace prose
- from: " / near nasals"
  to: " / [+nasal]_, _[+nasal] ; near nasals"
  reason: replace prose
- from: " / when not near emphatics"
  to: " / ! _[+ emphatic], [+ emphatic]_"
  reason: replace prose
- from: " / in Mentasta Ahtna"
  to: " / sporadic ; in Mentasta Ahtna"
  reason: replace prose
- from: " / in certain situations"
  to: " / sporadic ; in certain situations"
  reason: replace prose
- from: " / in some dialects"
  to: " / sporadic ; in some dialects"
  reason: replace prose
- from: " / in some northern"
  to: " / sporadic ; in some northern"
  reason: replace prose
- from: " / in northern dialects"
  to: " / sporadic ; in northern dialects"
  reason: replace prose
- from: " / in southern regions"
  to: " / sporadic ; in southern regions"
  reason: replace prose
- from: " / in southern dialects"
  to: " / sporadic ; in southern dialects"
  reason: replace prose
- from: " / in Nelemwa"
  to: " / sporadic ; in Nelemwa"
  reason: replace prose
- from: " / Pije and Fwai"
  to: " / sporadic ; Pije and Fwai"
  reason: replace prose
- from: " (in southern dialects"
  to: " sporadic ; (in southern dialects"
  reason: replace prose
- from: " (in some regions"
  to: " sporadic ; (in some regions"
  reason: replace prose
- from: " (some dialects"
  to: " sporadic ; (some dialects"
  reason: replace prose
- from: " (most dialects"
  to: " ; (most dialects"
  reason: replace prose
- from: " / “in some positions”"
  to: " / sporadic ; “in some positions”"
  reason: replace prose
- from: " ! in Ware Sekani"
  to: " sporadic ; not in Ware Sekani"
  reason: replace prose
- from: " ! in Queensland"
  to: " sporadic ; not in Queensland"
  reason: replace prose
- from: " / depending on the environment"
  to: " / sporadic ; depending on the environment"
  reason: replace prose
- from: " / (“when in unstressed penult"
  to: " / sporadic ; (“when in unstressed penult"
  reason: replace prose
- from: " / some sequences"
  to: " / sporadic ; some sequences"
  reason: replace prose
- from: " (some exceptions"
  to: " ; sporadic (some exceptions"
  reason: replace prose
- from: ", in the feminine ending"
  to: " sporadic ; in the feminine ending"
  reason: replace prose
- from: " / in Form VI"
  to: " / sporadic ; in Form VI"
  reason: replace prose
- from: " / _Ra (short a only)"
  to: " / _Ra sporadic ; (short a only)"
  reason: replace prose
- from: " / “[b]etween the last two vowels of a proparoxytone”"
  to: " / sporadic ; “[b]etween the last two vowels of a proparoxytone”"
  reason: replace prose
- from: There seems to ahve been some stuff going on
  to: " ; There seems to ahve been some stuff going on"
- from: (Do not necessarily
  to: " ;  (Do not necessarily"
  reason: comment
- from: " (“[a]rchaic relic”)"
  to: " ; (“[a]rchaic relic”)"
  reason: comment
- from: " / when stem-final"
  to: " / _%# ; when stem-final"
  reason: replace prose - this is an approximation and may be wrong
- from: " / when-stem final"
  to: " / _%# ; when-stem final"
  reason: replace prose - this is an approximation and may be wrong
- from: " (→ yː sometimes)"
  to: " → yː / sporadic ; (→ yː sometimes)"
  reason: workaround - we can't handle different envs for chained rules
- from: " (→ i in most descendants"
  to: " → i / sporadic ; (→ i in most descendants"
  reason: workaround - we can't handle different envs for chained rules
- from: " (not sure what "
  to: " ; (not sure what "
  reason: comment
- from: " “(before a prefix; "
  to: " ; “(before a prefix; "
  reason: comment
- from: " (note that PAn might "
  to: " ; (note that PAn might "
  reason: comment
- from: " (again, "
  to: " ; (again, "
  reason: comment
- from: " (Blevins "
  to: " ; (Blevins "
  reason: comment
- from: " (first change marked "
  to: " ; (first change marked "
  reason: comment
- from: " (?; included here based on "
  to: " ; (?; included here based on "
  reason: comment
- from: " (at least one instance of "
  to: " ; (at least one instance of "
  reason: comment
- from: " (conditioning unclear)"
  to: ' " / sporadic ; (conditioning unclear)"'
  reason: comment
- from: " / syllable-initially (h → ɦ?)"
  to: " / $_ ; (h → ɦ?)"
  reason: replace prose
- from: " / syllable-initially"
  to: " / $_ "
  reason: "replace "
- from: " / if short and unstressed"
  to: " / [-long, -stress]"
  reason: replace prose
- from: "k ʃk → k* kː / V_V "
  to: "ʃk → kː / V_V ; k ʃk → k* kː / V_V "
  reason: unresolvable symbol
- from: w (→ b?) → m
  to: w → b → m
  reason: chaining
- from: VN → V[+nasal] → V → (?)
  to: VN → V[+nasal] → V
  reason: unresolvable symbol
- from: " (→ b seems more common)"
  to: " ; (→ b seems more common)"
  reason: replace prose
- from: (kʷ → ɡʷ → ɡ ?)
  to: kʷ → ɡʷ → ɡ / sporadic ; (kʷ → ɡʷ → ɡ ?)
  reason: workaround
- from: C[+ affricate]
  to: O:[+delrel]
  reason: asca syntax replacement
- from: " (velar fricative is conjectured"
  to: " ; (velar fricative is conjectured"
  reason: comment
- from: " (fricative changes to approximant)"
  to: " ; (fricative changes to approximant)"
  reason: comment
- from: " (Whimemsz says"
  to: " ; (Whimemsz says"
  reason: comment
- from: "*L"
  to: L
  reason: liquids - may be too broad
- from: " ʰS "
  to: " Sʰ "
  reason:
    I have no idea what ʰS  is supposed to represent - I'm assuming it's a typo
    for Sʰ
- from: + A POA
  to: α place
  reason: Point of articulation - asca syntax alpha notation
- from: + B POA
  to: β place
  reason: Point of articulation - asca syntax alpha notation
- from: ATR
  to: atr
  reason: Lowercase feature name
- from: RTR
  to: rtr
  reason: Lowercase feature name
- from: " / only when short, ! "
  to: " / [-long] ! "
  reason: replace prose
- from: " / near gutturals"
  to: " / _[+laryngeal], [+laryngeal]_"
  reason: replace prose
- from: " / in two cases cited"
  to: " / sporadic ; in two cases cited"
  reason: replace prose
- from: " / in some "
  to: " / sporadic ; in some "
  reason: replace prose
- from: " / in inland varieties"
  to: " / sporadic ; in inland varieties"
  reason: replace prose
- from: " / in diminutives"
  to: " / sporadic ; diminutives"
  reason: replace prose
- from: " / in nominal suffixes"
  to: " / sporadic ; nominal suffixes"
  reason: replace prose
- from: " / in nouns"
  to: " / sporadic ; in nouns"
  reason: replace prose
- from: ", in some words"
  to: " sporadic ; in some words"
  reason: replace prose
- from: " / in coda"
  to: " / :{ _#, _% }: ; in coda"
  reason: replace prose
- from: " / possible exception"
  to: " / sporadic ; possible exception"
  reason: replace prose
- from: " / unclear conditioning"
  to: " / sporadic ; unclear conditioning"
  reason: replace prose
- from: " (seems to be a sporadic change"
  to: " ; (seems to be a sporadic change"
- from: ", in Milyan"
  to: " ; , in Milyan"
  reason: comment
- from: " / in "
  to: " / "
  reason: replace prose
- from: " ! in "
  to: " ! "
  reason: replace prose
- from: " (*)"
  to: " ; (*)"
  reason: ambiguous symbol
- from: "[anything]"
  to: "[]"
  reason: Use asca syntax for a wildcard symbol
- from: "_ or when _"
  to: "_,_"
  reason: replace prose
- from: "“under to [sic] the influence of neighboring consonants”"
  to: "/ sporadic ; “under to [sic] the influence of neighboring consonants”"
  reason: replace prose
- from: ", often"
  to: " ; , often"
  reason: replace prose
